name: ServerCommon Automation

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:

  precheck:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # -------------------------------------
      # INSTALL SERVICES
      # -------------------------------------

      - name: Install MySQL Redis Nginx
        run: |
          sudo apt update

          sudo apt install -y \
            mysql-server \
            redis-server \
            nginx

          sudo systemctl start mysql
          sudo systemctl start redis-server
          sudo systemctl start nginx

      # -------------------------------------
      # INSTALL PYTHON PACKAGES
      # -------------------------------------

      - name: Install Python Packages
        run: |
          pip install -r requirements.txt

      # -------------------------------------
      # RUN PRECHECK
      # -------------------------------------

      - name: Execute ServerCommon Checks
        run: |
          python scripts/precheck.py

      # -------------------------------------
      # SEND CLIQ MESSAGE
      # -------------------------------------

      - name: Send To Cliq
        env:
          CLIQ_WEBHOOK: ${{ secrets.CLIQ_WEBHOOK }}
        run: |
          python scripts/send_cliq.py

      # -------------------------------------
      # SAVE REPORT
      # -------------------------------------

      - name: Upload Report
        uses: actions/upload-artifact@v4
        with:
          name: server-report
          path: reports/server_report.json